In [13]:
import numpy as np
import pandas as pd
import seaborn as sns
import glob as glob

In [14]:
pd.set_option('display.max_columns',None)

## Reading multiple files to create a single DataFrame for Casualties

In [58]:
files2 = glob.glob("rd - casualty-*.csv")
files2

['rd - casualty-2017.csv',
 'rd - casualty-2018.csv',
 'rd - casualty-2019.csv',
 'rd - casualty-2020.csv',
 'rd - casualty-2021.csv']

In [60]:
casualties = pd.concat([pd.read_csv(f, low_memory=False) for f in files2], ignore_index=True)
casualties

,accident_index,accident_year,accident_reference,vehicle_reference,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,pedestrian_location,pedestrian_movement,car_passenger,bus_or_coach_passenger,pedestrian_road_maintenance_worker,casualty_type,casualty_home_area_type,casualty_imd_decile,lsoa_of_casualty
0,2017010001708,2017,010001708,1,1,2,2,18,4,3,0,0,1,0,0,9,1,2,NaN
1,2017010001708,2017,010001708,2,2,1,1,19,4,2,0,0,0,0,0,2,-1,-1,NaN
2,2017010001708,2017,010001708,2,3,2,1,18,4,1,0,0,0,0,0,2,-1,-1,NaN
3,2017010009342,2017,010009342,1,1,2,2,33,6,3,0,0,1,0,0,9,1,5,NaN
4,2017010009344,2017,010009344,3,1,1,2,31,6,3,0,0,0,0,0,9,1,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728536,2021991196607,2021,991196607,1,1,1,1,38,7,3,0,0,0,0,0,9,2,5,-1
728537,2021991196607,2021,991196607,2,2,1,1,61,9,3,0,0,0,0,0,9,2,9,-1
728538,2021991197944,2021,991197944,1,1,2,2,11,3,3,0,0,2,0,0,9,3,5,-1
728539,2021991200639,2021,991200639,1,1,3,2,34,6,3,1,3,0,0,0,0,1,1,-1
728540,2021991201030,2021,991201030,2,1,1,1,58,9,3,0,0,0,0,0,17,3,5,-1

In [62]:
casualties['casualty_type'].unique()

array([ 9,  2,  0,  3,  8,  1, 11,  4, 90, 19,  5, 10, 21, 20, 16, 98, 23,
       22, 17, 97, 18, 99, -1], dtype=int64)

In [63]:
casualties[casualties['casualty_type'] == 23]

,accident_index,accident_year,accident_reference,vehicle_reference,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,pedestrian_location,pedestrian_movement,car_passenger,bus_or_coach_passenger,pedestrian_road_maintenance_worker,casualty_type,casualty_home_area_type,casualty_imd_decile,lsoa_of_casualty
32521,2017030161828,2017,030161828,2,1,1,1,43,7,3,0,0,0,0,0,23,1,5,NaN
33211,2017030206114,2017,030206114,2,1,1,1,16,4,2,0,0,0,0,0,23,1,5,NaN
63467,2017140162289,2017,140162289,1,1,1,1,50,8,3,0,0,0,0,0,23,-1,-1,NaN
63864,2017140173092,2017,140173092,1,1,1,1,27,6,2,0,0,0,0,0,23,1,2,NaN
63990,2017140177902,2017,140177902,1,1,1,1,16,4,2,0,0,0,0,0,23,1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
721666,2021622100664,2021,622100664,1,1,1,1,25,5,2,0,0,0,0,0,23,1,1,W01001886
721668,2021622100666,2021,622100666,2,2,1,1,31,6,3,0,0,0,0,0,23,1,4,W01001709
722422,202163A074121,2021,63A074121,1,1,1,1,21,5,2,0,0,0,0,0,23,-1,-1,-1
728036,2021991116831,2021,991116831,1,1,1,1,19,4,3,0,0,0,0,0,23,1,1,-1
728092,2021991118056,2021,991118056,1,1,1,1,44,7,2,0,0,0,0,0,23,-1,-1,-1

In [66]:
(casualties['casualty_type'] ==2018).sum()

0

In [71]:
casualties.groupby('accident_year')['age_of_casualty'].unique()

accident_year
2017    [18, 19, 33, 31, 3, 45, 14, 58, 27, 39, 48, 26...
2018    [50, 48, 29, 40, 27, 43, 58, 69, 56, 60, 41, 3...
2019    [58, -1, 24, 21, 68, 47, 16, 20, 41, 25, 40, 2...
2020    [31, 2, 4, 23, 47, 32, 33, 25, 41, 50, 62, 37,...
2021    [19, 25, 21, 17, 27, 28, 20, 49, 37, 42, 30, 5...
Name: age_of_casualty, dtype: object

In [74]:
casualties[('casualty_severity')].unique()

array([3, 2, 1], dtype=int64)

In [77]:
casualties[(casualties['casualty_type'] == 97) & (casualties['accident_year']==2018)]

,accident_index,accident_year,accident_reference,vehicle_reference,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,pedestrian_location,pedestrian_movement,car_passenger,bus_or_coach_passenger,pedestrian_road_maintenance_worker,casualty_type,casualty_home_area_type,casualty_imd_decile,lsoa_of_casualty
201552,2018030275791,2018,030275791,1,1,1,1,47,8,2,0,0,0,0,0,97,1,4,NaN
201667,2018030281739,2018,030281739,1,1,1,1,39,7,3,0,0,0,0,0,97,1,1,NaN
201668,2018030281739,2018,030281739,1,3,2,1,52,8,3,0,0,0,0,0,97,1,1,NaN
201669,2018030281739,2018,030281739,1,4,2,1,53,8,3,0,0,0,0,0,97,1,1,NaN
201969,2018030300962,2018,030300962,1,1,1,1,52,8,3,0,0,0,0,0,97,-1,-1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323413,201891SNH1836,2018,91SNH1836,2,1,1,1,55,8,2,0,0,0,0,0,97,-1,-1,NaN
323530,201891SNM1896,2018,91SNM1896,1,1,1,1,53,8,2,0,0,0,0,0,97,-1,-1,NaN
323763,201891SNP2807,2018,91SNP2807,1,1,1,2,99,11,3,0,0,0,0,0,97,-1,-1,NaN
323783,201891SNP3661,2018,91SNP3661,2,1,1,1,56,9,3,0,0,0,0,0,97,-1,-1,NaN
324099,2018921800406,2018,921800406,2,1,1,1,25,5,3,0,0,0,0,0,97,-1,-1,NaN

In [78]:
casualties[(casualties['casualty_type'] == 97) & (casualties['accident_year'] == 2019)].count()

accident_index                        223
accident_year                         223
accident_reference                    223
vehicle_reference                     223
casualty_reference                    223
casualty_class                        223
sex_of_casualty                       223
age_of_casualty                       223
age_band_of_casualty                  223
casualty_severity                     223
pedestrian_location                   223
pedestrian_movement                   223
car_passenger                         223
bus_or_coach_passenger                223
pedestrian_road_maintenance_worker    223
casualty_type                         223
casualty_home_area_type               223
casualty_imd_decile                   223
lsoa_of_casualty                        0
dtype: int64

## Reading multiple files to create a single DataFrame for Accidents

In [45]:
files = glob.glob("rd - accident-*.csv")
files

['rd - accident-2017.csv',
 'rd - accident-2018.csv',
 'rd - accident-2019.csv',
 'rd - accident-2020.csv',
 'rd - accident-2021.csv']

In [46]:
# Reading multiple files to create a single DataFrame
accidents = pd.concat([pd.read_csv(f, low_memory=False) for f in files], ignore_index=True)

In [47]:
accidents

,accident_index,accident_year,accident_reference,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,accident_severity,number_of_vehicles,number_of_casualties,date,day_of_week,time,local_authority_district,local_authority_ons_district,local_authority_highway,first_road_class,first_road_number,road_type,speed_limit,junction_detail,junction_control,second_road_class,second_road_number,pedestrian_crossing_human_control,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location
0,2017010001708,2017,010001708,532920.0,196330.0,-0.080107,51.650061,1,1,2,3,05/08/2017,7,03:12,32,E09000010,E09000010,3,105,6,30,0,-1,-1,-1,0,0,4,1,1,0,0,1,1,2,E01001450
1,2017010009342,2017,010009342,526790.0,181970.0,-0.173845,51.522425,1,3,2,1,01/01/2017,1,01:30,1,E09000033,E09000033,3,5,6,30,3,4,6,0,0,0,4,1,2,0,0,1,1,2,E01004702
2,2017010009344,2017,010009344,535200.0,181260.0,-0.052969,51.514096,1,3,3,1,01/01/2017,1,00:30,5,E09000030,E09000030,3,13,6,30,3,4,5,0,0,0,4,1,1,0,0,1,1,2,E01004298
3,2017010009348,2017,010009348,534340.0,193560.0,-0.060658,51.624832,1,3,2,1,01/01/2017,1,01:11,32,E09000010,E09000010,3,1010,1,30,1,4,4,154,0,4,4,2,2,0,0,1,1,2,E01001429
4,2017010009350,2017,010009350,533680.0,187820.0,-0.072372,51.573408,1,2,1,1,01/01/2017,1,01:42,4,E09000012,E09000012,3,107,3,20,6,2,3,10,0,5,4,1,2,0,0,1,1,2,E01001808
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562434,2021991196247,2021,991196247,325546.0,674548.0,-3.194076,55.958152,99,3,2,1,22/09/2021,4,09:05,-1,S12000036,S12000036,6,0,6,20,3,4,6,0,0,0,1,1,1,0,0,1,1,-1,-1
562435,2021991196607,2021,991196607,271195.0,558271.0,-4.010304,54.902512,99,3,2,2,11/09/2021,7,21:15,-1,S12000006,S12000006,3,711,6,60,0,-1,0,-1,0,0,6,1,1,0,0,2,1,-1,-1
562436,2021991197944,2021,991197944,357297.0,860768.0,-2.716825,57.634805,99,3,1,1,17/04/2021,7,14:30,-1,S12000034,S12000034,4,9022,6,60,9,3,6,0,0,0,1,1,1,0,0,2,1,-1,-1
562437,2021991200639,2021,991200639,326936.0,675925.0,-3.172192,55.970735,99,3,1,1,17/09/2021,6,17:00,-1,S12000036,S12000036,3,901,9,20,3,2,3,901,0,5,1,9,1,0,0,1,2,-1,-1
562438,2021991201030,2021,991201030,270574.0,556367.0,-4.019126,54.885252,99,3,2,1,15/10/2021,6,16:15,-1,S12000006,S12000006,3,711,6,60,0,-1,0,-1,0,0,1,1,1,4,0,2,1,-1,-1

In [18]:
accidents['local_authority_highway'].unique()

array(['E09000010', 'E09000033', 'E09000030', 'E09000012', 'E09000027',
       'E09000017', 'E09000003', 'E09000022', 'E09000014', 'E09000009',
       'E09000028', 'E09000007', 'E09000016', 'E09000032', 'E09000013',
       'EHEATHROW', 'E09000026', 'E09000002', 'E09000011', 'E09000024',
       'E09000031', 'E09000006', 'E09000029', 'E09000005', 'E09000019',
       'E09000008', 'E09000004', 'E09000018', 'E09000025', 'E09000021',
       'E09000020', 'E09000015', 'E09000023', 'E09000001', 'E10000006',
       'E10000017', 'E06000008', 'E06000009', 'E08000015', 'E08000012',
       'E08000014', 'E08000011', 'E08000013', 'E08000010', 'E08000007',
       'E08000009', 'E08000003', 'E08000006', 'E08000008', 'E08000001',
       'E08000002', 'E08000005', 'E08000004', 'E06000049', 'E06000007',
       'E06000050', 'E06000006', 'E08000022', 'E08000021', 'E08000020',
       'E08000023', 'E06000048', 'E08000024', 'E06000005', 'E06000047',
       'E10000023', 'E06000014', 'E08000032', 'E08000036', 'E08000035',
       'E08000034', 'E08000033', 'E08000017', 'E08000018', 'E08000019',
       'E08000016', 'E06000010', 'E06000011', 'E06000012', 'E06000013',
       'E06000001', 'E06000003', 'E06000002', 'E06000004', 'E08000025',
       'E08000030', 'E08000029', 'E08000028', 'E08000031', 'E08000027',
       'E08000026', 'E10000028', 'E06000021', 'E06000051', 'E10000034',
       'E06000019', 'E06000020', 'E10000031', 'E10000007', 'E06000015',
       'E10000024', 'E06000018', 'E10000019', 'E10000018', 'E06000016',
       'E06000017', 'E10000021', 'E10000003', 'E06000031', 'E10000020',
       '-1', 'E10000029', 'E06000056', 'E06000055', 'E06000032',
       'E10000015', 'E10000012', 'E06000034', 'E06000033', 'E10000025',
       'E06000042', 'E10000002', 'E06000037', 'E06000039', 'E06000040',
       'E06000041', 'E06000038', 'E06000036', 'E06000045', 'E06000044',
       'E10000014', 'E06000046', 'E10000030', 'E10000016', 'E06000035',
       'E10000011', 'E10000032', 'E06000043', 'E10000008', 'E06000052',
       'E06000026', 'E06000027', 'E06000053', 'E06000024', 'E10000027',
       'E06000023', 'E06000022', 'E06000025', 'E10000013', 'E06000054',
       'E06000030', 'E06000028', 'E10000009', 'E06000029', 'W06000005',
       'W06000006', 'W06000001', 'W06000004', 'W06000003', 'W06000002',
       'W06000022', 'W06000018', 'W06000021', 'W06000019', 'W06000020',
       'W06000014', 'W06000015', 'W06000011', 'W06000016', 'W06000013',
       'W06000024', 'W06000012', 'W06000010', 'W06000023', 'W06000009',
       'W06000008', 'S12000017', 'S12000013', 'S12000023', 'S12000027',
       'S12000034', 'S12000020', 'S12000033', 'S12000024', 'S12000042',
       'S12000041', 'S12000015', 'S12000010', 'S12000040', 'S12000019',
       'S12000036', 'S12000026', 'S12000030', 'S12000005', 'S12000014',
       'S12000043', 'S12000011', 'S12000009', 'S12000038', 'S12000018',
       'S12000035', 'S12000039', 'S12000044', 'S12000029', 'S12000021',
       'S12000008', 'S12000028', 'S12000006'], dtype=object)

In [22]:
accidents[(accidents['local_authority_highway'] == '-1') & (accidents['accident_year'] == 2018)]

,accident_index,accident_year,accident_reference,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,accident_severity,number_of_vehicles,number_of_casualties,date,day_of_week,time,local_authority_district,local_authority_ons_district,local_authority_highway,first_road_class,first_road_number,road_type,speed_limit,junction_detail,junction_control,second_road_class,second_road_number,pedestrian_crossing_human_control,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location
204608,2018370256350,2018,370256350,589233.0,257460.0,0.766560,52.182936,37,2,1,1,03/01/2018,4,16:55,414,E07000204,-1,6,0,9,30,0,-1,-1,-1,0,0,6,4,2,0,0,2,1,2,E01030138
204610,2018370258201,2018,370258201,630021.0,234111.0,1.346445,51.957890,37,2,2,1,13/01/2018,7,14:50,415,E07000205,-1,6,0,6,30,0,-1,-1,-1,0,0,1,1,1,0,0,1,1,2,E01030163
204612,2018370260290,2018,370260290,596051.0,276118.0,0.876985,52.348090,37,2,1,3,19/01/2018,6,08:55,414,E07000204,-1,5,0,6,60,0,-1,-1,-1,0,0,1,1,4,0,0,2,1,2,E01030096
204615,2018370260720,2018,370260720,628938.0,233979.0,1.330624,51.957152,37,3,1,1,01/01/2018,2,00:35,415,E07000205,-1,6,0,6,30,0,-1,-1,-1,0,0,4,1,2,0,0,1,1,2,E01030171
204617,2018370260794,2018,370260794,572895.0,274215.0,0.536418,52.338781,37,3,1,1,02/01/2018,3,18:04,411,E07000201,-1,3,11,1,70,1,4,3,1065,0,0,4,2,2,0,0,2,1,1,E01029945
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206065,2018370828800,2018,370828800,628150.0,263476.0,1.338900,52.222225,37,3,1,1,13/12/2018,5,15:10,415,E07000205,-1,4,1116,6,30,3,4,6,0,0,0,1,1,1,0,0,2,2,2,E01030172
206066,2018370829955,2018,370829955,571316.0,272719.0,0.512503,52.325840,37,2,2,2,30/12/2018,1,09:34,411,E07000201,-1,3,11,3,60,3,4,6,0,0,0,1,1,1,0,0,2,1,1,E01029945
206067,2018370833307,2018,370833307,653551.0,295931.0,1.734475,52.502299,37,3,2,1,20/06/2018,4,18:25,416,E07000206,-1,6,0,6,30,3,4,6,0,2,4,1,1,1,0,0,1,1,2,E01030242
206068,2018370835221,2018,370835221,653170.0,293717.0,1.727193,52.482614,37,3,2,2,31/07/2018,3,21:39,416,E07000206,-1,3,1117,6,30,1,4,3,1117,0,0,4,1,1,0,0,1,1,2,E01030271
206069,2018370841831,2018,370841831,654903.0,293229.0,1.752284,52.477430,37,3,1,1,20/12/2018,5,10:46,416,E07000206,-1,6,0,6,20,0,-1,-1,-1,0,0,1,1,2,0,0,1,1,2,E01030249

In [25]:
accidents[(accidents['police_force'] == 37) & (accidents['accident_year'] == 2018)]

,accident_index,accident_year,accident_reference,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,accident_severity,number_of_vehicles,number_of_casualties,date,day_of_week,time,local_authority_district,local_authority_ons_district,local_authority_highway,first_road_class,first_road_number,road_type,speed_limit,junction_detail,junction_control,second_road_class,second_road_number,pedestrian_crossing_human_control,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location
204607,2018370256025,2018,370256025,603468.0,243203.0,0.965972,52.049866,37,2,2,1,05/01/2018,6,17:45,410,E07000200,E10000029,4,1070,6,60,1,4,3,1071,0,0,4,1,1,0,0,2,1,2,E01029893
204608,2018370256350,2018,370256350,589233.0,257460.0,0.766560,52.182936,37,2,1,1,03/01/2018,4,16:55,414,E07000204,-1,6,0,9,30,0,-1,-1,-1,0,0,6,4,2,0,0,2,1,2,E01030138
204609,2018370258121,2018,370258121,616763.0,245762.0,1.161178,52.067803,37,3,2,1,06/01/2018,7,23:40,412,E07000202,E10000029,6,0,6,30,0,-1,-1,-1,0,0,4,1,1,0,0,1,2,2,E01030011
204610,2018370258201,2018,370258201,630021.0,234111.0,1.346445,51.957890,37,2,2,1,13/01/2018,7,14:50,415,E07000205,-1,6,0,6,30,0,-1,-1,-1,0,0,1,1,1,0,0,1,1,2,E01030163
204611,2018370259744,2018,370259744,613482.0,243914.0,1.112231,52.052487,37,3,3,2,06/01/2018,7,17:32,412,E07000202,E10000029,6,0,6,30,0,-1,-1,-1,0,0,4,1,2,0,0,2,2,2,E01029984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206065,2018370828800,2018,370828800,628150.0,263476.0,1.338900,52.222225,37,3,1,1,13/12/2018,5,15:10,415,E07000205,-1,4,1116,6,30,3,4,6,0,0,0,1,1,1,0,0,2,2,2,E01030172
206066,2018370829955,2018,370829955,571316.0,272719.0,0.512503,52.325840,37,2,2,2,30/12/2018,1,09:34,411,E07000201,-1,3,11,3,60,3,4,6,0,0,0,1,1,1,0,0,2,1,1,E01029945
206067,2018370833307,2018,370833307,653551.0,295931.0,1.734475,52.502299,37,3,2,1,20/06/2018,4,18:25,416,E07000206,-1,6,0,6,30,3,4,6,0,2,4,1,1,1,0,0,1,1,2,E01030242
206068,2018370835221,2018,370835221,653170.0,293717.0,1.727193,52.482614,37,3,2,2,31/07/2018,3,21:39,416,E07000206,-1,3,1117,6,30,1,4,3,1117,0,0,4,1,1,0,0,1,1,2,E01030271
206069,2018370841831,2018,370841831,654903.0,293229.0,1.752284,52.477430,37,3,1,1,20/12/2018,5,10:46,416,E07000206,-1,6,0,6,20,0,-1,-1,-1,0,0,1,1,2,0,0,1,1,2,E01030249

In [38]:
accidents.isna().sum()

accident_index                                   0
accident_year                                    0
accident_reference                               0
location_easting_osgr                          133
location_northing_osgr                         133
longitude                                      143
latitude                                       143
police_force                                     0
accident_severity                                0
number_of_vehicles                               0
number_of_casualties                             0
date                                             0
day_of_week                                      0
time                                             0
local_authority_district                         0
local_authority_ons_district                     0
local_authority_highway                          0
first_road_class                                 0
first_road_number                                0
road_type                                        0
speed_limit                                      0
junction_detail                                  0
junction_control                                 0
second_road_class                                0
second_road_number                               0
pedestrian_crossing_human_control                0
pedestrian_crossing_physical_facilities          0
light_conditions                                 0
weather_conditions                               0
road_surface_conditions                          0
special_conditions_at_site                       0
carriageway_hazards                              0
urban_or_rural_area                              0
did_police_officer_attend_scene_of_accident      0
trunk_road_flag                                  0
lsoa_of_accident_location                        0
dtype: int64

In [54]:
accidents.groupby('accident_year').count()

,accident_index,accident_reference,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,accident_severity,number_of_vehicles,number_of_casualties,date,day_of_week,time,local_authority_district,local_authority_ons_district,local_authority_highway,first_road_class,first_road_number,road_type,speed_limit,junction_detail,junction_control,second_road_class,second_road_number,pedestrian_crossing_human_control,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location
accident_year,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2017,129982,129982,129963,129963,129953,129953,129982,129982,129982,129982,129982,129982,129982,129982,129982,129982,129982,129982,129982,129982,129982,129982,129982,129982,129982,129982,129982,129982,129982,129982,129982,129982,129982,129982,129982
2018,122635,122635,122580,122580,122580,122580,122635,122635,122635,122635,122635,122635,122635,122635,122635,122635,122635,122635,122635,122635,122635,122635,122635,122635,122635,122635,122635,122635,122635,122635,122635,122635,122635,122635,122635
2019,117536,117536,117508,117508,117508,117508,117536,117536,117536,117536,117536,117536,117536,117536,117536,117536,117536,117536,117536,117536,117536,117536,117536,117536,117536,117536,117536,117536,117536,117536,117536,117536,117536,117536,117536
2020,91199,91199,91185,91185,91185,91185,91199,91199,91199,91199,91199,91199,91199,91199,91199,91199,91199,91199,91199,91199,91199,91199,91199,91199,91199,91199,91199,91199,91199,91199,91199,91199,91199,91199,91199
2021,101087,101087,101070,101070,101070,101070,101087,101087,101087,101087,101087,101087,101087,101087,101087,101087,101087,101087,101087,101087,101087,101087,101087,101087,101087,101087,101087,101087,101087,101087,101087,101087,101087,101087,101087